<?php
/**
 * @file
 * Module to demonstrate the Productivity_Title profile.
 */


/**
 * Group name for the migration classes.
 */
define('PRODUCTIVITY_MIGRATION_GROUP', 'productivity');

/**
 * Implements hook_migrate_api().
 */
function productivity_migrate_migrate_api() {
  $classes = array(
    'ProductivityMigrateProject',
    'ProductivityMigrateAccount',
  );

  $migrations = array();
  foreach ($classes as $class_name) {
    $migrations[$class_name] = array(
      'class_name' => $class_name,
      'group_name' => PRODUCTIVITY_MIGRATION_GROUP,
    );
  }

  $api = array(
    'api'        => 2,
    'groups'     => array(
      PRODUCTIVITY_MIGRATION_GROUP => array(
        'title' => t('Content'),
      ),
    ),
    'migrations' => $migrations,
  );

  return $api;
}
