<?php
/**
 * @file
 * Code for the productivity account feature.
 */

include_once 'productivity_account.features.inc';

/**
 * Get all employee user IDs.
 */
function productivity_account_get_employee_uids() {
  // Get all active employees.
  $query = new EntityFieldQuery();
  $result = $query
    ->entityCondition('entity_type', 'user')
    ->propertyCondition('status', 1)
    ->fieldCondition('field_employment_status', 'value', 'employed')
    ->propertyOrderBy('name')
    ->execute();

  if (empty($result['user'])) {
    return array();
  }

  return array_keys($result['user']);
}
