<?php
/**
 * @file
 * Code for the productivity account feature.
 */

include_once 'productivity_account.features.inc';

/**
 * Get all employee user IDs.
 */
function productivity_account_get_employee_uids() {
  // Get all active employees.
  $query = new EntityFieldQuery();
  $result = $query
    ->entityCondition('entity_type', 'user')
    ->propertyCondition('status', 1)
    ->propertyOrderBy('name')
    ->execute();

  if (empty($result['user'])) {
    return array();
  }

  return array_keys($result['user']);
}

/**
 * Get all employee list.
 */
function productivity_account_get_employees_list() {
  $query = db_select('users', 'u');
  $query->fields('u', array('uid', 'name'));
  $result = $query->execute()->fetchAllKeyed();
  return $result;
}
