<?php

include_once 'productivity_user.features.inc';

/**
 * @file
 * Drupal needs this blank file.
 */
/**
 * Implements hook_init().
 */
function productivity_user_init() {
  if (!productivity_user_is_live()) {
    global $conf;
    // Set test mail.
    if (!empty($conf['mail_system'])) {
      foreach ($conf['mail_system'] as $system => $class) {
        $conf['mail_system'][$system] = 'CatchTestMailSystem';
      }
    }
  }
}


/**
 * Check if we are in live environment.
 */
function productivity_user_is_live() {
  if (!(defined('PANTHEON_ENVIRONMENT') && PANTHEON_ENVIRONMENT == 'live')) {
    return FALSE;
  }
  return TRUE;
}

/**
 * Get all active user for give year and month.
 */
function productivity_user_get_active_uids($month, $year) {
  $start_timestamp =  $year . '-' . $month. '-01'. ' 00:00:00';

  // We need to add a second quer since value2 of date has a default of value(1).
  $query_not_active = new EntityFieldQuery();
  $query_not_active->entityCondition('entity_type', 'user')
    ->fieldCondition('field_job_type', 'value', array('developer', 'qa'), 'IN')
    ->fieldCondition('field_employment_status', 'value', 'employed', '!=')
    ->fieldCondition('field_date', 'value2', $start_timestamp, '<=');
  $result_inactives = $query_not_active->execute();
  $uids = FALSE;
  if (isset($result_inactives['user'])) {
    $uids = array_keys($result_inactives['user']);
  }

  // Run a second query to overcome the date field endtime.
  $query_start = new EntityFieldQuery();
  $query_start->entityCondition('entity_type', 'user')
    ->fieldCondition('field_job_type', 'value', array('developer', 'qa'), 'IN')
    ->fieldCondition('field_date', 'value', $start_timestamp, '<=');

  if ($uids) {
    $query_start->propertyCondition('uid', $uids, 'NOT IN');
  }
  $result_start = $query_start->execute();


  if (isset($result_start['user'])) {
    return array_keys($result_start['user']);
  }

  return array();
}
