<?php
/**
 * @file
 * Code for the Productivity time tracking feature.
 */

include_once 'productivity_time_tracking.features.inc';

/**
 * hook_form_FORM_ID_alter().
 *
 * Add custom field to the system information admin form.
 */
function productivity_time_tracking_form_system_site_information_settings_alter(&$form, &$form_state, $form_id) {
  $form['hours_count_as_day'] = array(
    '#type' => 'textfield',
    '#title' => t('Hours to count as one day'),
    '#default_value' => variable_get('hours_count_as_day'),
  );
}

/**
 * Get general days in a given month.
 */
function productivity_time_tracking_get_global_days($month, $year) {
  // Call the restfull service.
  $handler = restful_get_restful_handler('tracking');
  $request = array();
  $request['year'] = $year;
  $request['month'] = $month;
  $request['global'] = TRUE;
  $result = $handler->get('', $request);

  // Normalize global days.
  $assoc_globals = array();
  foreach ($result as $gday) {
    $assoc_globals[$gday['day']] = array(
      'id' => 'new',
      'length' => 'G',
      'projectName' => $gday['description'],
    );
  }
  return $assoc_globals;
}

/**
 * Save tracking using service.
 */
function productivity_time_tracking_save($timestamp, $employee, $project_nid) {
  // Call the restfull service.
  $handler = restful_get_restful_handler('tracking');
  $request = array();
  $request['date'] = $timestamp;
  $request['employee'] = $employee;
  $request['projectID'] = $project_nid;
  $request['type'] = 'regular';
  $request['length'] = 8.0;
  $request['period'] = 'hour';

  $result = $handler->post('', $request);

  return $result;
}

/**
 * Total hours done in a project.
 *
 * @param $project_nid
 * @param array $date_range
 * @param array $employees
 * @return array
 */
function productivity_time_tracking_get_employee_tracking_count($strtime, $employee) {
  $query = new EntityFieldQuery();
  $account = user_load_by_name($employee);
  $query->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'time_tracking')
    ->propertyCondition('status', NODE_PUBLISHED)
    ->fieldCondition('field_work_date', 'value', $strtime)
    ->fieldCondition('field_employee', 'target_id', $account->uid)
    ->count();

  return $query->execute();
}

/**
 * Calculate the number of days on a certain project.
 *
 * Counts number of entries which has a certain number of hours (hours_count_as_day)
 * as days and sums up the remaining hours and divides them on "hours_count_as_day"
 * to calculate the number of the remaining days.
 *
 * @param $project_nid
 *    The node ID of the project.
 *
 * @return float|mixed
 *    The number of days in the project.
 */
function productivity_time_tracking_total_days($project_nid, $date = array()) {
  // If the variable "hours_count_as_day" is not set, The default day is 8 Hours.
  $hours_as_day = variable_get('hours_count_as_day') ? variable_get('hours_count_as_day') : 8;
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'time_tracking')
    ->propertyCondition('status', NODE_PUBLISHED)
    ->fieldCondition('field_track_hours', 'value', $hours_as_day, '>=')
    ->fieldCondition('field_project', 'target_id', $project_nid)
    ->count();

  if (!empty($date)) {
    $start_date =  $date['year'] . '-' . $date['month'] . '-01'. ' 00:00:00';
    $end_date = date('Y-m-d 00:00:00', strtotime('+1 month', strtotime($start_date)));
    $query->fieldCondition('field_work_date', 'value', $start_date, '>=');
    $query->fieldCondition('field_work_date', 'value', $end_date, '<');
  }

  $days = $query->execute();

  // Calculate the remaining hours in the project.
  $fragments_query = db_select('field_data_field_track_hours','h');
  $fragments_query
    ->leftJoin('field_data_field_project', 'p', 'h.entity_id = p.entity_id');
  // If Date range is given, calculate within that period.
  if (!empty($date)) {
    $fragments_query
      ->leftJoin('field_data_field_work_date', 'd', 'h.entity_id = d.entity_id');
    $fragments_query
      ->condition("field_work_date_value", $start_date, '>=')
      ->condition("field_work_date_value", $end_date, '<');
  }

  $fragments_query
    ->condition("field_track_hours_value", $hours_as_day, '<')
    ->condition('field_project_target_id', $project_nid, '=');


  $fragments_query->addExpression('SUM(field_track_hours_value)', 'sum_of_hours');

  $remaining_hours = $fragments_query->execute()->fetchAll();

  if (!empty($remaining_hours)) {
    $days = ($remaining_hours[0]->sum_of_hours / $hours_as_day) + $days;
  }

  return $days;
}

/**
 * Total hours done in a project.
 *
 * @param $project_nid
 * @param array $date
 * @param bool $account
 * @param array $employees
 *
 * @return array
 */
function productivity_time_tracking_total_hours($project_nid, $date = array(),  $account = FALSE, $employees = array()) {
  if (!$account) {
    global $user;
    $account = $user;
  }
  $query = new EntityFieldQuery();

  $query->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'time_tracking')
    ->propertyCondition('status', NODE_PUBLISHED)
    ->fieldCondition('field_day_type', 'value', 'regular')
    ->addMetaData('account', $account)
    ->fieldCondition('field_project', 'target_id', $project_nid);

  if (!empty($date)) {
    $start_date =  $date['year'] . '-' . $date['month'] . '-01'. ' 00:00:00';
    $end_date = date('Y-m-d 00:00:00', strtotime('+1 month', strtotime($start_date)));
    $query->fieldCondition('field_work_date', 'value', $start_date, '>=');
    $query->fieldCondition('field_work_date', 'value', $end_date, '<');
  }

  $result = $query->execute();

  $total = array(
    'day' => 0,
    'hour' => 0,
  );
  if (!isset($result['node'])) {
    return $total;
  }

  foreach ($result['node'] as $res) {
    $wrapper = entity_metadata_wrapper('node', $res->nid);
    $total['hour'] += $wrapper->field_track_hours->value();
  }
  $total['day'] = productivity_time_tracking_total_days($project_nid);
  return $total;
}

/**
 * Implements hook_node_presave().
 *
 * Set the node title automatically.
 * Update parent project's days/hours accordingly.
 */
function productivity_time_tracking_node_presave($node) {
  if ($node->type == 'time_tracking') {
    $wrapper = entity_metadata_wrapper('node', $node);
    $title =
      date('d M Y', $wrapper->field_work_date->value()) . ' - ' .
      ($wrapper->__isset('field_employee') ? ($wrapper->field_employee->label() . '-') : '') .
      ($wrapper->__isset('field_project') ? ($wrapper->field_project->label() . '-') : '') .
      $wrapper->field_day_type->value();
    $wrapper->title->set($title);

    // Add days/hours to parent project's total.
    if ($wrapper->field_day_type->value() == 'regular') {
      $project_wrapper = $wrapper->field_project;
      $hours = $project_wrapper->field_hours->value() ? $project_wrapper->field_hours->value() : 0;
      if (!$node->is_new) {
        $hours -= $node->original->field_track_hours[LANGUAGE_NONE][0]['value'];
      }
      $hours += $wrapper->field_track_hours->value();

      $project_wrapper->field_hours->set($hours);
      $project_wrapper->field_days->set(productivity_time_tracking_total_days($project_wrapper->getIdentifier()));
      $project_wrapper->save();
    }
  }
}

/**
 * Implements hook_menu().
 *
 * Callback for mailgun.
 */
function productivity_time_tracking_menu() {
  $items = array();
  // Create a time tracking node(s) from mailGun JSON.
  $items['mailgun/get-tracking'] = array(
    'title' => 'Create time tracking',
    'access arguments' => array('access content'),
    'page callback' => 'productivity_time_tracking_mail_create',
    'access callback' => 'user_is_anonymous',
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Upload file.
 */
function productivity_time_tracking_mail_create() {
  if (empty($_POST['X-Mailgun-Incoming']) || $_POST['X-Mailgun-Incoming'] != 'Yes') {
    watchdog('productivity_time_tracking', 'Return #46, $_POST[X-Mailgun-Incoming]: <pre>'. $_POST['X-Mailgun-Incoming'] .'</pre>');
    return;
  }
  $message = message_create('mailgun_incoming_mail', array(
    'arguments' => array(
      '@text' => print_r($_POST, TRUE)
    )
  ));
  $wrapper = entity_metadata_wrapper('message', $message);
  $wrapper->save();
  // TODO: Save tracking entity.
}

/**
 * Send message to user if he/she doesn't have tracking for yesterday.
 *
 * @param $account
 *  User object.
 */
function productivity_time_tracking_send_reminder($account) {
  // Get the yesterday date.
  $yesterday_starts = date('Y-m-d 00:00:00', strtotime('-1 days'));
  $yesterday_ends = date('Y-m-d 23:59:59', strtotime('-1 days'));

  $query = new EntityFieldQuery();
  $result = $query
    ->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'time_tracking')
    ->propertyCondition('status', NODE_PUBLISHED)
    ->propertyCondition('uid', $account->uid)
    ->fieldCondition('field_work_date', 'value', $yesterday_starts, '>=')
    ->fieldCondition('field_work_date', 'value', $yesterday_ends, '<=')
    ->execute();
  $no_records = TRUE;
  if ($result) {
    return;
  }

  if ($no_records) {
    $values = array(
      'subject' => 'Productivity',
      'uid' => $account->uid
    );
    $message = message_create('mail_reminder', $values);

    $wrapper = entity_metadata_wrapper('user', $account);

    $wrapper->field_last_notification->set(time());
    $wrapper->save();
    // Send mail to users
    message_notify_send_message($message);
  }
}

/**
 * Implements hook_cron().
 *
 * Send reminder to existing developers,
 * That did not filled time tracking yesterday.
 */
function productivity_time_tracking_cron() {

  $now = date('H', time());
  $timetosend = explode('-', variable_get('time_to_send_reminder', '9-13'));
  if (intval($now) < $timetosend[0] || intval($now) > $timetosend[1]) {
    // Send notifications in defined time period.
    return;
  }

  $weekend = variable_get('productivity_weekend', '5,6');
  $days = explode(',', $weekend);
  $dw = date('N', strtotime('-1 days'));
  // Yesterday was weekend, so there shouldn't be any records.
  foreach($days as $day) {
    if ($dw == $day) {
      return;
    }
  }

  // Select users that don't have time tracking records during the whole
  // previous day.

  // Get all active developers, that should have tracking.
  $query = new EntityFieldQuery();
  $result = $query
    ->entityCondition('entity_type', 'user')
    ->propertyCondition('status', 1)
    ->fieldCondition('field_job_type', 'value', 'developer')
    ->fieldCondition('field_employment_status', 'value', 'employed')
    ->execute();

  if (empty($result['user'])) {
    // There are no active employed developers.
    return;
  }

  $accounts = user_load_multiple(array_keys($result['user']));
  foreach ($accounts as $account) {
    // Check if this user has already got notification today.
    $wrapper = entity_metadata_wrapper('user', $account);
    if ($wrapper->field_last_notification->value() >= strtotime(date('Y-m-d 00:00:00', time()))) {
      // Notification has been already sent today.
      continue;
    }
    productivity_time_tracking_send_reminder($account);
  }
}
