<?php

/**
 * Implements hook_migrate_api().
 */
function productivity_migrate_migrate_api() {
  $classes = array(
    'ProductivityMigrateAccount',
    'ProductivityMigratePayment',
    'ProductivityMigrateProject',
    'ProductivityMigrateSessionTypes',
    'ProductivityMigrateTimewatchUser',
    'ProductivityMigrateTracker',
    'ProductivityMigrateUser',
  );

  $migrations = array();
  foreach ($classes as $class_name) {
    $migrations[$class_name] = array(
      'class_name' => $class_name,
      'group_name' => 'productivity',
    );
  }

  $api = array(
    'api' => 2,
    'groups' => array(
      'productivity' => array(
        'title' => t('Productivity'),
      ),
    ),
    'migrations' => $migrations,
  );

  return $api;
}
